apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    run: mywebapp
spec:
  type: LoadBalancer
  ports:
  - port:  80            # map port 80 in the service to the container port 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: mywebapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3        
  selector:
    matchLabels:
      run: mywebapp
  template:
    metadata:
      labels:
        run: mywebapp
    spec:
      containers:
      - name: mysql
        image: mysql
        env: 
        - name:MYSQL_ROOT_PASSWORD  
          value:password
        - name:MYSQL_DATABASE
          value:myDB
          
        ports:
        - containerPort:80        # expose the MySQL default port 
      - name: webapp
        image: mywebapp                 # set the image name
        ports:
        - containerPort: 8080